### ISSUE TITLE
无法添加未收录

### ISSUE THREAD

**Issue by ivysrono** [iberryful/weixin_sogou#2]
比方说 「厚大司考」/houdask 这个未收录都没有
或者是「清法LAWYERS」，未收录
点击 add ，总是提示「添加失败, 请点此重试」，重试也没用。
firefox 39 x64，win8.1 x64

**Comment by taoalpha** [comment]
嗨, add按钮是用来直接输入openid添加的~ 你可以通过搜索 名称 然后点击结果的添加来添加~

清法LAWYERS 我已经帮你添加啦

**Comment by ivysrono** [comment]
@taoalpha 谢谢，我知道怎么添加了。
但还是很奇怪，为何微信号为「houdask」的公众号「厚大司考」搜索里面完全找不到？

**Comment by iberryful** [comment]
@renyouguo 有的公众号搜不到，是搜狗的原因，一般来说没有认证的账号是搜不到的
