### ISSUE TITLE
js解析是不是有问题呢

### ISSUE THREAD

**Issue by z55heihei** [iberryful/weixin_sogou#3]
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x104bd4ad0>> ignored 
这个是不是搜狗的反爬虫了

**Comment by iberryful** [comment]
不是触发了反爬虫，js解析的方式会自动处理cookies

**Comment by z55heihei** [comment]
我想问下 加载下一页有什么好思路么

**Comment by iberryful** [comment]
@z55heihei 用phantomjs 模拟点击事件，我没有试过，感觉应该不难

**Comment by z55heihei** [comment]
是啊 我也是这样想的 我看你做的rss.me的网站的加载更多好像不太准 比如我收一个公众号文章 搜狗上有10篇 你那边好像少于10篇 你那个是随机给的么

**Comment by iberryful** [comment]
@z55heihei 不是随机的，新收录的公众号抓取文章有一定的延迟
